# Generated by Django 4.2.1 on 2023-10-27 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjectsapp', '0002_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subjectsapp.course')),
            ],
        ),
    ]
