# Generated by Django 4.2.1 on 2023-10-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='inUse',
            field=models.BooleanField(default=False),
        ),
    ]
