# Generated by Django 4.2.1 on 2023-12-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rfid_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
